# Generated by Django 2.1.2 on 2018-11-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=30)),
                ('book_price', models.IntegerField()),
                ('book_author', models.CharField(max_length=50)),
                ('created_at', models.DateField()),
            ],
        ),
    ]
